# Generated by Django 5.2.7 on 2025-11-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookShop", "0003_alter_orderedproduct_user_delete_userinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.URLField(max_length=500),
        ),
    ]
