# Generated by Django 5.2.7 on 2025-11-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookShop", "0004_product_stock_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderedproduct",
            name="amount",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
