# Generated by Django 5.2.8 on 2025-11-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BookShop", "0006_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
    ]
