# Generated by Django 5.2.8 on 2025-11-24 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookShop", "0007_remove_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderedproduct",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="BookShop.order",
            ),
        ),
    ]
